# Generated by Django 3.0 on 2023-02-07 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_auto_20230207_0020'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactdata',
            old_name='message',
            new_name='text',
        ),
    ]
