# Generated by Django 3.0 on 2023-01-30 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='is_posted',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
