# Generated by Django 3.0 on 2023-02-03 02:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='user_like_project',
            field=models.ManyToManyField(blank=True, related_name='user_like_proj', to=settings.AUTH_USER_MODEL),
        ),
    ]
