# Generated by Django 3.0 on 2023-02-03 02:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_project_user_like_project'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='user_like_project',
            new_name='user_like_proj',
        ),
    ]
